version: "2.4"
services:
  wrp:
    build: .
    image: wrp:wrp
    read_only: true
    ports: 
      - "8080:8080/tcp"
    cap_drop:
      - ALL
    command: -g 640x400x16 -t gif
    mem_limit: 200M
    # cpus: 0.5
    tmpfs:
      - /tmp

